# Generated by Django 3.2.4 on 2021-07-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TIENDAKAA', '0003_carrito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
